#license
SHWZ_LICENSE_PATH: license.lic
SHWZ_LICENSE_PUBLIC_CERT_PATH: publiccerts.keystore

#oauth2
SHWZ_OATH2_CLIENT_ID: shwz_app
SHWZ_OATH2_CLIENT_SECRET: shwz_secret
SHWZ_OATH2_CLIENT_SCOPE: server

#redis
SHWZ_REDIS_URL: 172.26.202.82
SHWZ_REDIS_PORT: 35672
SHWZ_RABBITMQ_USER: admin
SHWZ_RABBITMQ_PASS: admin

#servlet  上传文件大小控制 100m
SHWZ_SERVLET_MaxFileSize: 104857600
SHWZ_SERVLET_MaxRequestSize: 104857600

#rabbitmq
SHWZ_RABBITMQ_URL: 172.26.202.82
SHWZ_RABBITMQ_PORT: 35672
SHWZ_RABBITMQ_USER: admin
SHWZ_RABBITMQ_PASS: admin

#db
SHWZ_DB_DRIVER_CLASS: oracle.jdbc.driver.OracleDriver
SHWZ_DB_USER: SHWZ_ADMIN
SHWZ_DB_PASS: SHWZ_ADMIN
SHWZ_DB_JDBC_URL: oracle:thin:@192.168.16.74:1521/orcl
SHWZ_DB_DS_NAME: dataSource
SHWZ_DB_DS_TYPE: Oracle
SHWZ_HIKARI_MAX_POOL: 10
SHWZ_HIKARI_MAX_LIFE: 60
SHWZ_HIKARI_MIN_IDLE: 5
SHWZ_HIKARI_IDLE_TIMEOUT: 300000
SHWZ_HIKARI_CONN_TIMEOUT: 45000
SHWZ_HIKARI_TEST_QUERY: select 1 from dual
SHWZ_HIKARI_VALIDATE_TIMEOUT: 30000

#erp
SHWZ_ERP_Username: temp================
SHWZ_ERP_Password: xi123456
SHWZ_ERP_WEBSERVICE_URL: http://10.130.24.235:50100/XISOAPAdapter/MessageServlet?channel=:BoWeiWZFZZC_Services:BoWeiWZFZZC_Sender&version=3.0&Sender.Service=BoWeiWZFZZC_Services&Interface=urn%3Asmepc-com%3Awzfz%5EZps18FmGczjPublicReq_MI
SHWZ_ERP_WEBSERVICE_QUERY: urn:smepc-com:wzfz
SHWZ_ERP_WEBSERVICE_METHOD: Zps18FmGczjPublicReq_MT
SHWZ_ERP_WEBSERVICE_DEBUG: true



    